import Head from "next/head";
import styles from "./styles/main.css"
import SearchBar from "./components/SearchBar";

export default function Page() {
    return (
      <>
        <Head>
          <title>IncluSITE</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
          <script src="queries.js"></script>
        </Head>

        <main className={`${styles.container}`}>
          <div className={`${styles.windowImage}`}>

            <h1>IncluSITE</h1>

          </div>

          <SearchBar></SearchBar>




        </main>





      </>
            

    )
  }
  