"use client";

import Head from "next/head";
// import "../app/styles/main.css"
import styles from "./styles/main.module.css";
import Filters from "./components/Filters";
// import FilterBox from "./components/FilterBox";
import SearchBar from "./components/SearchBar";
import {useState} from "react";
import SearchResultsList from "./components/SearchResultsList";

export default function Page() {
  const [results, setResults] = useState([]);


    return (
      <>
        {/* <Head>
          <title>IncluSITE</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head> */}

        {/* <main className={`${styles.container}`}>
          <div className={`${styles.windowImage}`}>

            <h1>IncluSITE</h1>

          </div>

          <div className="search-bar-container">
            <SearchBar setResults={setResults}></SearchBar>
            {results && results.length > 0 && <SearchResultsList results={results} />}
          </div>
          <div>
            <h2>Filter for Accessibility Features</h2>

            // <FilterBox text="Arias, Image Descriptions, and Screen-reader Support"></FilterBox> 
            <input type="checkbox" value="visual"></input>
            <label htmlFor="aria">Arias, Image Descriptions, and Screen-reader Support</label>

            <input type="checkbox" value="audio"></input>
            <label htmlFor="audio">Video Captioning</label>

            <input type="checkbox" value="lowvision"></input>
            <label htmlFor="lowvision">Text and Color Contrast</label>
          </div>

        </main> */}

        <Head>
          <title>IncluSITE</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.container}>
          <h1>IncluSITE</h1>

          <div className="search-bar-container">
            <SearchBar setResults={setResults}></SearchBar>
            {/* {results && results.length > 0 && <SearchResultsList results={results} />} */}
          </div>

          <div className={styles.columns}>
            <div className={styles.left}>
              <Filters></Filters>
            </div>

            <div className={styles.right}>
              <h2>Results</h2>
              {results && results.length > 0 && <SearchResultsList results={results} />}

            </div>

          </div>


        </main>






      </>
            

    )
  }
  