"use client";

import Head from "next/head";
import styles from "./styles.css"
import SearchBar from "./components/SearchBar";
import {useState} from "react";
import SearchResultsList from "./components/SearchResultsList";

export default function Page() {
  const [results, setResults] = useState([]);
    return (
      <>
        <Head>
          <title>IncluSITE</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="stylesheet" href="styles.css"></link>
        </Head>

        <main className={`${styles.container}`}>
          <div className={`${styles.windowImage}`}>

            <h1>IncluSITE</h1>

          </div>
          <div className={`${styles.container}`}>
            <div className="search-bar-container">
              <SearchBar setResults={setResults}></SearchBar>
              {results && results.length > 0 && <SearchResultsList results={results} />}
            </div>
            <div className={`${styles.filters}`}>
            </div>
          </div>

          

        </main>





      </>
            

    )
  }
  